apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-app
  namespace: argocd
spec:
  project: multi-app-project
  source:
    repoURL: https://github.com/KiNgM347/ArgoCD.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: test-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
