apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multi-app-project
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: test-argo
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
