apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multi-app-project
  namespace: argocd  # Namespace in cui è installato ArgoCD
spec:
  # Definizione dei namespace in cui le applicazioni possono essere deployate
  destinations:
  - namespace: test-argo  # Namespace in cui verranno deployate le app
    server: https://kubernetes.default.svc
  # Repository da cui le applicazioni saranno caricate
  sourceRepos:
  - https://github.com/KiNgM347/ArgoCD.git  # Repository del codice
